### PR TITLE
Add option to write output directly to a file

### PR DESCRIPTION
**Pull request by piranna**
Add an option to set a file where output will be send instead of stdout.

### CODE REVIEW

**Comment by alexfernandez** [comment]
Please add a description with the new option name.

Also, please document it in the README, with an example.

**Comment by piranna** [comment]
Where should I put the description?

**Comment by alexfernandez** [comment]
In this same PR.

**Comment by piranna** [comment]
Added description. I've also send a new commit with the updated README.md.

**Comment by alexfernandez** [comment]
Good! Only one minor point left: "Options" should start with a capital "O".

**Comment by piranna** [comment]
Done ;-)

**Comment by alexfernandez** [comment]
Thanks!

**Comment by piranna** [comment]
You are welcome :-) Can you confirm me when get's published?

**Comment by alexfernandez** [comment]
Done! Just published version 1.1.0 with your changes.

**Comment by piranna** [comment]
Wiii!!! ^^ Thank you! :-D

**Pull request merged**
